name: Shalabs First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greetings
        run:  echo "Hello World!"
      - name: Multiple commands
        run: |
            sysdet=$(uname -a)
            echo "System details : ${sysdet}"
            echo
            nodev=$(node -v)
            echo "Node version : ${node}"
            echo
            npmv=$(npm -v)
            echo "npm version : ${npmv}"
            pyver=$(python --version)
            echo "Python Version : ${pyvar}"
            echo
      - name: Print goodbye
        run: echo "Done - Bye!"
