name: Shalabs First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greetings
        run:  echo "Hello World!"
      - name: Multiple commands
        run: |
            uname -a
            echo
            uptime
            echo
            node -v
            echo
            npm -v
            echo 
            python --version
      - name: Print goodbye
        run: echo "Done - Bye!"
