name: Shalabs First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greetings
        run:  echo "Hello World!"
      - name: Pring sysinfo
        run: |
            uname -a
            echo
            uptime
            echo
      - name: Print goodbye
        run: echo "Done - Bye!"
