name: Test Var
run-name: Test Var
on:
    workflow_dispatch:
        inputs:
         DEPLOYMENT_ENVIORNMENT:
            description: 'Deployment Env of Infra. Expected values are ''dev'', ''test'', ''pro'''
            default: 'dev'
            type: choice
            options:
            - 'dev'
            - 'test'
            - 'prod'

jobs:
    First:
        runs-on: ubuntu-latest
        steps:
            - name: echo the value
              shell: bash
              run: |
                date
                touch /tmp/${{ inputs.DEPLOYMENT_ENVIORNMENT }}_app.log
                seq 1024 > /tmp/${{ inputs.DEPLOYMENT_ENVIORNMENT }}_app.log
                du -sh /tmp/${{ inputs.DEPLOYMENT_ENVIORNMENT }}_app.log
                echo
                ls -lhrt /tmp/${{ inputs.DEPLOYMENT_ENVIORNMENT }}_app.log
